# project_id = "your-new-project-id"

[functions.notify-waitlist]
verify_jwt = false

[functions.detect-available-spots]
verify_jwt = false

[functions.bulk-create-students]
verify_jwt = true

[functions.bulk-create-classes]
verify_jwt = true

[functions.intelligent-bulk-create-classes]
verify_jwt = true

[functions.stripe-connect]
verify_jwt = true

[functions.stripe-login-link]
verify_jwt = true